### PR TITLE
Create table if non-existent, use "open" on masOS

### PR DESCRIPTION
**Pull request by mjhanninen**
Hi Justin, noticed this on #haskhel. Here are couple little tweaks I had to make to get it run on my MBP.  Most notably:

- Create the `watched` table if the database is missing it.
- Spawn `open` instead of `explorer` on macOS.

### CODE REVIEW

**Comment by justinwoo** [comment]
thanks!!

just to provide some more info:

i'm using the schema `CREATE TABLE watched (path varchar(20) primary key unique, created datetime);`, and i have a whole bunch of code churn on my end. sorry i didn't see this pr earlier! i can rebase it and merge it in if you'd like me to.

**Comment by justinwoo** [comment]
here's a quick rebase i did if you'd like to look at it and reset the author :D https://github.com/justinwoo/vidtracker/commit/05808be8584ec64d6df93045c0536840da8c62ec

**Comment by mjhanninen** [comment]
Thanks. Updated.

**Comment by justinwoo** [comment]
thanks!!

**Pull request merged**
